name: Check, Lint, Format, Type-check and Test

on:
  pull_request:
    branches: ["main"]

jobs:
  check-lint-format-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: corepack enable && yarn install
      - name: Type check project
        run: yarn check
      - name: Lint project
        run: yarn lint
      - name: Format project
        run: yarn format
      - name: Test project
        run: yarn test
      - name: Check for Changes
        id: check_changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "Changes detected."
            echo "::set-output name=has_changes::true"
          else
            echo "No changes detected."
            echo "::set-output name=has_changes::false"
          fi
      - name: Commit and Push Changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # configure user
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          # stage any file changes to be committed
          git add .

          # make commit with staged changes
          git commit -m 'chore:check,  lint, format, and test project'

          # push the commit back up to source GitHub repository
          git push
